export const FETCH_BILLING_TABLE_DATA_BEGIN = "FETCH_BILLING_TABLE_DATA_BEGIN";
export const FETCH_BILLING_TABLE_DATA_SUCCESS =
  "FETCH_BILLING_TABLE_DATA_SUCCESS";
export const FETCH_BILLING_TABLE_DATA_FAILURE =
  "FETCH_BILLING_TABLE_DATA_FAILURE";

export const FETCH_GROUP_SERVICES_DATA_BEGIN =
  "FETCH_GROUP_SERVICES_DATA_BEGIN";
export const FETCH_GROUP_SERVICES_DATA_SUCCESS =
  "FETCH_GROUP_SERVICES_DATA_SUCCESS";
export const FETCH_GROUP_SERVICES_DATA_FAILURE =
  "FETCH_GROUP_SERVICES_DATA_FAILURE";

export const FETCH_GROUP_CHART_DATA_BEGIN = "FETCH_GROUP_CHART_DATA_BEGIN";
export const FETCH_GROUP_CHART_DATA_SUCCESS = "FETCH_GROUP_CHART_DATA_SUCCESS";
export const FETCH_GROUP_CHART_DATA_FAILURE = "FETCH_GROUP_CHART_DATA_FAILURE";

export const SELECT_BILLING_TABLE_ROW = "SELECT_BILLING_TABLE_ROW";
export const UNSELECT_BILLING_TABLE_ROW = "UNSELECT_BILLING_TABLE_ROW";

export const SET_BILLING_TABLE_PAGE_NUMBER = "SET_BILLING_TABLE_PAGE_NUMBER";
