stages:
  - build
  - lint
  - test
#  - deploy

pytest:
  stage: test
  script: docker-compose -f compose-test.yml down && docker-compose -f compose-test.yml build && docker-compose -f compose-test.yml run pytest

build:
  stage: build
  script: docker build . -t griphook

#push:
#  stage: deploy
#  script: docker tag griphook registry.gitlab.uaprom:7000/griphook/tasks && docker push registry.gitlab.uaprom:7000/griphook/tasks
#  only:
#    - master

flake8:
  stage: lint
  script: docker run griphook python manage.py flake
