stages:
#  - lint
  - test
  - deploy

pytest:
  stage: test
  script: docker-compose -f compose-test.yml build && docker-compose -f compose-test.yml run pytest

build:
  stage: deploy
  script: docker build . -t griphook

push:
  stage: deploy
  script: docker tag griphook registry.gitlab.uaprom:7000/griphook/tasks && docker push registry.gitlab.uaprom:7000/griphook/tasks

#flake8:
#  stage: lint
#  script:
#   - flake8 --exclude=griphook/db/migrations --show-source griphook/
#   - git diff HEAD^ | flake8 --diff # lint only changed files
