variables:
  KUBECONFIG: "/etc/kubernetes/admin.conf"
  REGISTY_URL: "registry.gitlab.uaprom:7000/griphook"

stages:
  - build
  - lint
  - test
  - deploy
  - clean_images

pytest:
  stage: test
  script: docker-compose -f compose-test.yml down && docker-compose -f compose-test.yml build && docker-compose -f compose-test.yml run pytest

build:
  stage: build
  script:
    - docker build . -t backend
    - docker build griphook/frontend -t frontend

push:
  stage: deploy
  script:
    - docker tag backend $REGISTY_URL/backend:$CI_COMMIT_SHA
    - docker push $REGISTY_URL/backend:$CI_COMMIT_SHA
    - docker tag frontend $REGISTY_URL/frontend:$CI_COMMIT_SHA
    - docker push $REGISTY_URL/frontend:$CI_COMMIT_SHA
    - echo $REGISTY_URL/frontend:$CI_COMMIT_SHA
  only:
    - kubernetes
    - master

clean_images:
  stage: clean_images
  script:
    - docker rm -f $(docker ps -a -q)
    - docker rmi -f $(docker images -q)

flake8:
  stage: lint
  script: docker run griphook python manage.py flake
