variables:
  KUBECONFIG: "/etc/kubernetes/admin.conf"
  REGISTY_URL: "registry.gitlab.uaprom:7000/griphook"

stages:
  - build
  - lint
  - test
  - push_images_to_registry
  - deploy

build:
  stage: build
  script:
    - docker build . -t backend
    - docker build griphook/frontend -t frontend

flake8:
  stage: lint
  script: docker run backend python manage.py flake

pytest:
  stage: test
  script: docker-compose -f compose-test.yml down && docker-compose -f compose-test.yml run pytest

.push: &image_push
  stage: push_images_to_registry
  script:
    - docker tag ${CI_JOB_NAME##*:} $REGISTY_URL/${CI_JOB_NAME##*:}:${CI_COMMIT_SHA:0:8}
    - docker push $REGISTY_URL/${CI_JOB_NAME##*:}:${CI_COMMIT_SHA:0:8}
  only:
    - master

push:frontend:
  <<: *image_push

push:backend:
  <<: *image_push

.deploy_template: &kube_apply
  stage: deploy
  before_script:
    - sed s/\CI_COMMIT_SHA/${CI_COMMIT_SHA:0:8}/ kubernetes/${CI_JOB_NAME##*:}.yml > $CI_JOB_NAME.yml
  script:
    -  kubectl  --kubeconfig $KUBECONFIG apply -f $CI_JOB_NAME.yml
  only:
    - master

deploy:postgres_deployment:
  <<: *kube_apply

deploy:backend_deployment:
  <<: *kube_apply

deploy:db_migration_job:
  <<: *kube_apply

deploy:rabbit_deployment:
  <<: *kube_apply

deploy:celery_deployment:
  <<: *kube_apply

deploy:task_scheduler_deployment:
  <<: *kube_apply

deploy:frontend_deployment:
  <<: *kube_apply