version: "2.1"
services:
    pytest:
        build: .
        depends_on:
            postgres:
                condition: service_healthy
            rabbit:
                condition: service_healthy
        environment:
            - GH_CELERY_BROKER_URL=amqp://guest:guest@rabbit
        healthcheck:
                test: "exit 0"
        command: bash -c "./entrypoint.sh upgrade && pytest"

    rabbit:
        image: rabbitmq
        healthcheck:
            test: "exit 0"

    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=user
            - POSTGRES_DB=database_name
        healthcheck:
            test: "exit 0"