version: "2.1"
services:
    pytest:
        build: .
        depends_on:
            postgres:
                condition: service_healthy
            rabbit:
                condition: service_healthy
        environment:
            - GH_CELERY_BROKER_URL=amqp://guest:guest@rabbit
            - GH_DATABASE_TEST_URL=postgres://user:password@postgres:5432/dbname
        healthcheck:
                test: "exit 0"
        command: bash -c "pytest"

    rabbit:
        image: rabbitmq
        healthcheck:
            test: "exit 0"

    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=user
            - POSTGRES_DB=dbname
        healthcheck:
            test: "exit 0"