version: "2.1"
services:
    celery_worker:
        image: t3
        depends_on:
            rabbit:
                condition: service_healthy
            postgres:
                condition: service_healthy
        environment:
            - GH_CELERY_BROKER_URL=amqp://guest:guest@rabbit
            - GH_DATABASE_URL=postgresql://user:password@postgres/database_name
        healthcheck:
                test: "exit 0"
        command: bash -c "alembic upgrade head && pytest"

    rabbit:
        image: rabbitmq
        healthcheck:
            test: "exit 0"

    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=user
            - POSTGRES_DB=database_name
        healthcheck:
            test: "exit 0"