api:
  GRAPHITE_URL: https://graphite.olympus.evo/render
db:
  DATABASE_URL: postgres://user:password@postgres:5432/database_name
  DATABASE_TEST_URL: postgres://user:password@postgres:5432/database_name
tasks:
  CELERY_BROKER_URL: ampq://user:password@localhost/root
  DATA_SOURCE_DATA_EXPIRES: 7776000
  MAX_PARSE_TASKS_IN_QUEUE: 24
  PARSE_METRIC_EXPIRES: 900
  FILLING_TASK_QUEUE_INTERVAL: 15
  CREATING_BATCHES_INTERVAL: 3600