version: "2.1"
services:
    celery_beat:
        restart: always
        image: test8
        depends_on:
            rabbit:
                condition: service_healthy
        environment:
            - GH_CELERY_BROKER_URL=amqp://guest:guest@rabbit
        command: celery -A griphook.tasks.tasks beat

    celery_worker:
        restart: always
        image: test8
        depends_on:
            rabbit:
                condition: service_healthy
        environment:
            - GH_CELERY_BROKER_URL=amqp://guest:guest@rabbit
        command: celery -A griphook.tasks.tasks worker -l INFO

    rabbit:
        restart: always
        image: rabbitmq
        healthcheck:
            test: "exit 0"