version: "2.1"
services:
    postgres:
      restart: always
      image: postgres
      ports:
        - 5432:5432
      volumes:
        - ./dev/postgres-data:/var/lib/postgresql/data
      environment:
          - POSTGRES_PASSWORD=griphook
          - POSTGRES_USER=griphook_admin
          - POSTGRES_DB=griphook
      healthcheck:
          test: "exit 0"

    postgres_test:
        image: postgres
        ports:
          - 5433:5432
        environment:
            - POSTGRES_PASSWORD=griphook
            - POSTGRES_USER=griphook_admin
            - POSTGRES_DB=test_griphook
        healthcheck:
            test: "exit 0"
    web:
      restart: always
      image: web
      build: .
      ports:
        - 5000:5000
      volumes:
        - ./:/etc/grip
      environment:
        - APP_NAME=griphook
        - FLASK_DEBUG=1
        - PYTHONUNBUFFERED=0
        - APP_SETTINGS=griphook.server.config.DevelopmentConfig
        - SECRET_KEY=change_me_in_prod
        - GH_DATABASE_URL=postgresql://griphook_admin:griphook@postgres/griphook
      depends_on:
        - postgres
      command: bash -c "gunicorn -c gunicorn_config.py  manage:app"

    frontend:
      restart: always
      build: griphook/frontend
      ports:
        - 82:82
      volumes:
        - ./griphook/frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./griphook/frontend/dist:/etc/nginx/dist/static/
      command: /bin/sh -c "sleep 5; nginx -g 'daemon off;'"