version: "2.1"
services:
#    celery_beat:
#        restart: always
#        build: .
#        depends_on:
#            rabbit:
#                condition: service_healthy
#            postgres:
#                condition: service_healthy
#        depends_on:
#            celery_worker:
#                condition: service_healthy
#        environment:
#            - GH_CELERY_BROKER_URL=amqp://guest:guest@rabbit
#            - GH_DATABASE_URL=postgresql://user:password@postgres/database_name
#        command: celery -A griphook.tasks.tasks beat
#
    celery_worker:
      restart: always
      build: .
      volumes:
        - ./:/etc/grip
      depends_on:
        rabbit:
          condition: service_healthy
        postgres:
          condition: service_healthy
      environment:
          - GH_CELERY_BROKER_URL=amqp://guest:guest@rabbit
          - GH_DATABASE_URL=postgresql://user:password@postgres/database_name
      healthcheck:
        test: "exit 0"
      command: bash -c "sleep 3 && python manage.py db upgrade && celery -A griphook.tasks.tasks worker -l INFO"

    task_scheduler:
      restart: always
      build: .
      volumes:
        - ./:/etc/grip
      depends_on:
        rabbit:
          condition: service_healthy
        postgres:
          condition: service_healthy
        celery_worker: 
          condition: service_healthy  
      environment:
          - GH_CELERY_BROKER_URL=amqp://guest:guest@rabbit
          - GH_DATABASE_URL=postgresql://user:password@postgres/database_name
      healthcheck:
        test: "exit 0"
      command: bash -c "sleep 3 && python griphook/tasks/task_scheduler.py"

    rabbit:
      restart: always
      image: rabbitmq
      healthcheck:
        test: "exit 0"

    postgres:
      restart: always
      image: postgres
      environment:
          - POSTGRES_PASSWORD=password
          - POSTGRES_USER=user
          - POSTGRES_DB=database_name
      healthcheck:
          test: "exit 0"

    web:
      restart: always
      image: web
      build: .
      ports:
        - 5002:5000
      volumes:
        - ./:/etc/grip
      environment:
        - APP_NAME=griphook
        - FLASK_DEBUG=1
        - PYTHONUNBUFFERED=0
        - APP_SETTINGS=griphook.server.config.DevelopmentConfig
        - SECRET_KEY=change_me_in_prod
      depends_on:
        - postgres
      command: bash -c "python manage.py run -h 0.0.0.0"
