version: "2.1"
services:
    celery_beat:
        restart: always
        build: .
        depends_on:
            rabbit:
                condition: service_healthy
        environment:
            - GH_CELERY_BROKER_URL=amqp://guest:guest@rabbit
        command: celery -A griphook.tasks.tasks beat

    celery_worker:
        restart: always
        #image: test8
        build: .
        depends_on:
            rabbit:
                condition: service_healthy
        environment:
            - GH_CELERY_BROKER_URL=amqp://guest:guest@rabbit
            - GH_LOGGER_HOST=logstash
            - GH_LOGGER_PORT=5044
        command: celery -A griphook.tasks.tasks worker -l INFO

    rabbit:
        restart: always
        image: rabbitmq
        healthcheck:
            test: "exit 0"

    elasticsearch:
        environment:
            http.host: 0.0.0.0
            transport.host: 127.0.0.1
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
        # networks:
        #     elk: null
        ports:
            - 9200:9200
        restart: unless-stopped
        volumes:
            - ./elasticsearch:/usr/share/elasticsearch/data

    logstash:
        image: docker.elastic.co/logstash/logstash-oss:6.2.1
        depends_on:
            - elasticsearch
        # networks:
        #     elk: null
        ports:
            - 5044:5044
        restart: unless-stopped
        volumes:
            - ./etc/logstash/pipeline:/usr/share/logstash/pipeline

    kibana:
        depends_on:
            - elasticsearch
        environment:
            ELASTICSEARCH_PASSWORD: changeme
            ELASTICSEARCH_URL: http://elasticsearch:9200
            ELASTICSEARCH_USERNAME: elastic
        image: docker.elastic.co/kibana/kibana-oss:6.2.1
        # networks:
        #     elk: null
        ports:
            - 5601:5601
        restart: unless-stopped