export const FETCH_PEAKS_CHART_DATA_BEGIN = "FETCH_PEAKS_CHART_DATA_BEGIN";
export const FETCH_PEAKS_CHART_DATA_SUCCESS = "FETCH_PEAKS_CHART_DATA_SUCCESS";
export const FETCH_PEAKS_CHART_DATA_FAILURE = "FETCH_PEAKS_CHART_DATA_FAILURE";

export const SET_PEAKS_CHART_METRIC_TYPE_OPTION =
  "SET_PEAKS_CHART_METRIC_TYPE_OPTION";
