export const FETCH_AVERAGE_LOAD_CHART_DATA_BEGIN =
  "FETCH_AVERAGE_LOAD_CHART_DATA_BEGIN";
export const FETCH_AVERAGE_LOAD_CHART_DATA_SUCCESS =
  "FETCH_AVERAGE_LOAD_CHART_DATA_SUCCESS";
export const FETCH_AVERAGE_LOAD_CHART_DATA_FAILURE =
  "FETCH_AVERAGE_LOAD_CHART_DATA_FAILURE";

export const SET_AVERAGE_LOAD_CHART_METRIC_TYPE_OPTION =
  "SET_AVERAGE_LOAD_CHART_METRIC_TYPE_OPTION";
