export const FETCH_FILTERS_HIERARCHY_BEGIN = "FETCH_FILTERS_HIERARCHY_BEGIN";
export const FETCH_FILTERS_HIERARCHY_SUCCESS =
  "FETCH_FILTERS_HIERARCHY_SUCCESS";
export const FETCH_FILTERS_HIERARCHY_FAILURE =
  "FETCH_FILTERS_HIERARCHY_FAILURE";

export const SELECT_CLUSTER_FILTER = "SELECT_CLUSTER_FILTER";
export const UNSELECT_CLUSTER_FILTER = "UNSELECT_CLUSTER_FILTER";
export const SELECT_SERVER_FILTER = "SELECT_SERVER_FILTER";
export const UNSELECT_SERVER_FILTER = "UNSELECT_SERVER_FILTER";
export const SELECT_SERVICES_GROUP_FILTER = "SELECT_SERVICES_GROUP_FILTER";
export const UNSELECT_SERVICES_GROUP_FILTER = "UNSELECT_SERVICES_GROUP_FILTER";
