"""Added User model

Revision ID: 0123422e176f
Revises: 6a729a017a42
Create Date: 2018-08-23 11:38:04.743562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0123422e176f'
down_revision = '6a729a017a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_constraint('teams_fk', 'metrics_billing', type_='foreignkey')
    op.drop_constraint('projects_fk', 'metrics_billing', type_='foreignkey')
    op.create_foreign_key('projects_fk', 'metrics_billing', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('teams_fk', 'metrics_billing', 'teams', ['team_id'], ['id'])
    op.drop_constraint('projects_fk', 'metrics_peaks', type_='foreignkey')
    op.drop_constraint('teams_fk', 'metrics_peaks', type_='foreignkey')
    op.create_foreign_key('teams_fk', 'metrics_peaks', 'teams', ['team_id'], ['id'])
    op.create_foreign_key('projects_fk', 'metrics_peaks', 'projects', ['project_id'], ['id'])
    op.drop_constraint('project_fk', 'services_groups', type_='foreignkey')
    op.drop_constraint('team_fk', 'services_groups', type_='foreignkey')
    op.create_foreign_key('team_fk', 'services_groups', 'teams', ['team_id'], ['id'])
    op.create_foreign_key('project_fk', 'services_groups', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_fk', 'services_groups', type_='foreignkey')
    op.drop_constraint('team_fk', 'services_groups', type_='foreignkey')
    op.create_foreign_key('team_fk', 'services_groups', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('project_fk', 'services_groups', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('projects_fk', 'metrics_peaks', type_='foreignkey')
    op.drop_constraint('teams_fk', 'metrics_peaks', type_='foreignkey')
    op.create_foreign_key('teams_fk', 'metrics_peaks', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('projects_fk', 'metrics_peaks', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('teams_fk', 'metrics_billing', type_='foreignkey')
    op.drop_constraint('projects_fk', 'metrics_billing', type_='foreignkey')
    op.create_foreign_key('projects_fk', 'metrics_billing', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('teams_fk', 'metrics_billing', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.drop_table('users')
    # ### end Alembic commands ###
