"""empty message

Revision ID: 408041f63149
Revises: cee172c05d7a
Create Date: 2018-08-29 17:42:04.982167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408041f63149'
down_revision = 'cee172c05d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_fk', 'metrics_billing', type_='foreignkey')
    op.drop_constraint('teams_fk', 'metrics_billing', type_='foreignkey')
    op.create_foreign_key('teams_fk', 'metrics_billing', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('projects_fk', 'metrics_billing', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('projects_fk', 'metrics_peaks', type_='foreignkey')
    op.drop_constraint('teams_fk', 'metrics_peaks', type_='foreignkey')
    op.create_foreign_key('teams_fk', 'metrics_peaks', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('projects_fk', 'metrics_peaks', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('team_fk', 'services_groups', type_='foreignkey')
    op.drop_constraint('project_fk', 'services_groups', type_='foreignkey')
    op.create_foreign_key('project_fk', 'services_groups', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('team_fk', 'services_groups', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_fk', 'services_groups', type_='foreignkey')
    op.drop_constraint('project_fk', 'services_groups', type_='foreignkey')
    op.create_foreign_key('project_fk', 'services_groups', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('team_fk', 'services_groups', 'teams', ['team_id'], ['id'])
    op.drop_constraint('projects_fk', 'metrics_peaks', type_='foreignkey')
    op.drop_constraint('teams_fk', 'metrics_peaks', type_='foreignkey')
    op.create_foreign_key('teams_fk', 'metrics_peaks', 'teams', ['team_id'], ['id'])
    op.create_foreign_key('projects_fk', 'metrics_peaks', 'projects', ['project_id'], ['id'])
    op.drop_constraint('projects_fk', 'metrics_billing', type_='foreignkey')
    op.drop_constraint('teams_fk', 'metrics_billing', type_='foreignkey')
    op.create_foreign_key('teams_fk', 'metrics_billing', 'teams', ['team_id'], ['id'])
    op.create_foreign_key('projects_fk', 'metrics_billing', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
