"""Added Admin model

Revision ID: f38ef55dfc5f
Revises: 6a729a017a42
Create Date: 2018-08-23 20:20:08.917106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f38ef55dfc5f'
down_revision = '6a729a017a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('metrics_billing', sa.Column('new_password', sa.Float(), nullable=False))
    op.drop_constraint('projects_fk', 'metrics_billing', type_='foreignkey')
    op.drop_constraint('teams_fk', 'metrics_billing', type_='foreignkey')
    op.create_foreign_key('teams_fk', 'metrics_billing', 'teams', ['team_id'], ['id'])
    op.create_foreign_key('projects_fk', 'metrics_billing', 'projects', ['project_id'], ['id'])
    op.drop_column('metrics_billing', 'value')
    op.add_column('metrics_peaks', sa.Column('new_password', sa.Float(), nullable=False))
    op.drop_constraint('teams_fk', 'metrics_peaks', type_='foreignkey')
    op.drop_constraint('projects_fk', 'metrics_peaks', type_='foreignkey')
    op.create_foreign_key('projects_fk', 'metrics_peaks', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('teams_fk', 'metrics_peaks', 'teams', ['team_id'], ['id'])
    op.drop_column('metrics_peaks', 'value')
    op.drop_constraint('team_fk', 'services_groups', type_='foreignkey')
    op.drop_constraint('project_fk', 'services_groups', type_='foreignkey')
    op.create_foreign_key('project_fk', 'services_groups', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('team_fk', 'services_groups', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_fk', 'services_groups', type_='foreignkey')
    op.drop_constraint('project_fk', 'services_groups', type_='foreignkey')
    op.create_foreign_key('project_fk', 'services_groups', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('team_fk', 'services_groups', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.add_column('metrics_peaks', sa.Column('value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint('teams_fk', 'metrics_peaks', type_='foreignkey')
    op.drop_constraint('projects_fk', 'metrics_peaks', type_='foreignkey')
    op.create_foreign_key('projects_fk', 'metrics_peaks', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('teams_fk', 'metrics_peaks', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.drop_column('metrics_peaks', 'new_password')
    op.add_column('metrics_billing', sa.Column('value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint('projects_fk', 'metrics_billing', type_='foreignkey')
    op.drop_constraint('teams_fk', 'metrics_billing', type_='foreignkey')
    op.create_foreign_key('teams_fk', 'metrics_billing', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('projects_fk', 'metrics_billing', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.drop_column('metrics_billing', 'new_password')
    op.drop_table('admins')
    # ### end Alembic commands ###
