export const FETCH_BILLING_PIE_CHART_ABSOLUTE_DATA_BEGIN =
  "FETCH_BILLING_PIE_CHART_ABSOLUTE_DATA_BEGIN";
export const FETCH_BILLING_PIE_CHART_ABSOLUTE_DATA_FAILURE =
  "FETCH_BILLING_PIE_CHART_ABSOLUTE_DATA_FAILURE";
export const FETCH_BILLING_PIE_CHART_ABSOLUTE_DATA_SUCCESS =
  "FETCH_BILLING_PIE_CHART_ABSOLUTE_DATA_SUCCESS";

export const FETCH_BILLING_PIE_CHART_RELATIVE_DATA_BEGIN =
  "FETCH_BILLING_PIE_CHART_RELATIVE_DATA_BEGIN";
export const FETCH_BILLING_PIE_CHART_RELATIVE_DATA_FAILURE =
  "FETCH_BILLING_PIE_CHART_RELATIVE_DATA_FAILURE";
export const FETCH_BILLING_PIE_CHART_RELATIVE_DATA_SUCCESS =
  "FETCH_BILLING_PIE_CHART_RELATIVE_DATA_SUCCESS";
