export const FETCH_BILLING_FILTERS_HIERARCHY_BEGIN =
  "FETCH_BILLING_FILTERS_HIERARCHY_BEGIN";
export const FETCH_BILLING_FILTERS_HIERARCHY_SUCCESS =
  "FETCH_BILLING_FILTERS_HIERARCHY_SUCCESS";
export const FETCH_BILLING_FILTERS_HIERARCHY_FAILURE =
  "FETCH_BILLING_FILTERS_HIERARCHY_FAILURE";

export const SET_BILLING_PROJECTS_FILTER_PAGE_NUMBER =
  "SET_BILLING_PROJECTS_FILTER_PAGE_NUMBER";
export const SET_BILLING_TEAMS_FILTER_PAGE_NUMBER =
  "SET_BILLING_TEAMS_FILTER_PAGE_NUMBER";
export const SET_BILLING_CLUSTERS_FILTER_PAGE_NUMBER =
  "SET_BILLING_CLUSTERS_FILTER_PAGE_NUMBER";
export const SET_BILLING_SERVERS_FILTER_PAGE_NUMBER =
  "SET_BILLING_SERVERS_FILTER_PAGE_NUMBER";
export const SET_BILLING_SERVICES_GROUPS_FILTER_PAGE_NUMBER =
  "SET_BILLING_SERVICES_GROUPS_FILTER_PAGE_NUMBER";
export const SET_BILLING_SERVICES_FILTER_PAGE_NUMBER =
  "SET_BILLING_SERVICES_FILTER_PAGE_NUMBER";
