export const FETCH_BILLING_FILTERS_HIERARCHY_BEGIN =
  "FETCH_BILLING_FILTERS_HIERARCHY_BEGIN";
export const FETCH_BILLING_FILTERS_HIERARCHY_SUCCESS =
  "FETCH_BILLING_FILTERS_HIERARCHY_SUCCESS";
export const FETCH_BILLING_FILTERS_HIERARCHY_FAILURE =
  "FETCH_BILLING_FILTERS_HIERARCHY_FAILURE";

export const SELECT_BILLING_CLUSTER_FILTER = "SELECT_BILLING_CLUSTER_FILTER";
export const UNSELECT_BILLING_CLUSTER_FILTER =
  "UNSELECT_BILLING_CLUSTER_FILTER";
export const SELECT_BILLING_SERVER_FILTER = "SELECT_BILLING_SERVER_FILTER";
export const UNSELECT_BILLING_SERVER_FILTER = "UNSELECT_BILLING_SERVER_FILTER";
export const SELECT_BILLING_SERVICES_GROUP_FILTER =
  "SELECT_BILLING_SERVICES_GROUP_FILTER";
export const UNSELECT_BILLING_SERVICES_GROUP_FILTER =
  "UNSELECT_BILLING_SERVICES_GROUP_FILTER";
