apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: celery
  namespace: griphook
spec:
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
        - image: registry.gitlab.uaprom:7000/griphook/backend:CI_COMMIT_SHA
          name: celery
          command: ["celery"]
          args: ["-A", "griphook.tasks.tasks", "worker", "-l", "INFO"]
          env:
            - name: GH_DATABASE_URL
              value: postgresql://griphook:griphook@postgres/griphook
            - name: GH_CELERY_BROKER_URL
              value: amqp://guest:guest@rabbitmq