apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: griphook
spec:
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
  selector:
    app: rabbitmq
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: griphook
spec:
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - image: rabbitmq
          name: rabbitmq
          ports:
            - containerPort: 5672
              name: rabbitmq