apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scheduler
  namespace: griphook
spec:
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - image: registry.gitlab.uaprom:7000/griphook/backend:CI_COMMIT_SHA
          name: scheduler
          command: ["python"]
          args: ["griphook/tasks/task_scheduler.py"]
          env:
            - name: GH_DATABASE_URL
              value: postgresql://griphook:griphook@postgres/griphook
            - name: GH_CELERY_BROKER_URL
              value: amqp://guest:guest@rabbitmq