export const SET_BILLING_TIME_FROM_OPTION = "SET_BILLING_TIME_FROM_OPTION";
export const SET_BILLING_TIME_UNTIL_OPTION = "SET_BILLING_TIME_UNTIL_OPTION";
export const SET_BILLING_METRIC_TYPE_OPTION = "SET_BILLING_METRIC_TYPE_OPTION";
export const SET_BILLING_TIME_STEP_OPTION = "SET_BILLING_TIME_STEP_OPTION";

export const SET_BILLING_TARGET_OPTION = "SET_BILLING_TARGET_OPTION";

export const ADD_GROUP_TO_TARGET_IDS = "ADD_GROUP_TO_TARGET_IDS";
export const REMOVE_GROUP_FROM_TARGET_IDS = "REMOVE_GROUP_FROM_TARGET_IDS";
