"""update_service_table

Revision ID: 34015815507b
Revises: ea6adb521616
Create Date: 2018-07-13 11:58:29.845057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34015815507b'
down_revision = 'ea6adb521616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('instance', sa.String(), nullable=True))
    op.add_column('services', sa.Column('server', sa.String(), nullable=True))
    op.create_unique_constraint('ut_1', 'services', ['title', 'instance', 'services_group_id', 'server'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ut_1', 'services', type_='unique')
    op.drop_column('services', 'server')
    op.drop_column('services', 'instance')
    # ### end Alembic commands ###
