"""update metric table add batch table

Revision ID: b8bd7cc08e65
Revises: fb6ca70ec66a
Create Date: 2018-07-18 12:21:52.897909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8bd7cc08e65'
down_revision = 'fb6ca70ec66a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches_story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('time')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.add_column('metrics', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.drop_constraint('metrics_type_id_service_id_time_from_key', 'metrics', type_='unique')
    op.create_foreign_key('batch_story_fk', 'metrics', 'batches_story', ['batch_id'], ['id'])
    op.drop_column('metrics', 'time_from')
    op.add_column('projects', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('services_groups', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key('team_fk', 'services_groups', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_fk', 'services_groups', type_='foreignkey')
    op.drop_column('services_groups', 'team_id')
    op.drop_column('projects', 'created')
    op.add_column('metrics', sa.Column('time_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint('batch_story_fk', 'metrics', type_='foreignkey')
    op.create_unique_constraint('metrics_type_id_service_id_time_from_key', 'metrics', ['type_id', 'service_id', 'time_from'])
    op.drop_column('metrics', 'batch_id')
    op.drop_table('teams')
    op.drop_table('batches_story')
    # ### end Alembic commands ###
