"""initial

Revision ID: bfc202f272db
Revises: 
Create Date: 2018-07-25 14:47:21.034778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc202f272db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches_story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('put_into_queue', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('time')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('services_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='project_fk'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='team_fk'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('instance', sa.String(), nullable=True),
    sa.Column('server', sa.String(), nullable=True),
    sa.Column('cluster', sa.String(), nullable=True),
    sa.Column('services_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['services_group_id'], ['services_groups.id'], name='services_group_fk'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'instance', 'services_group_id', 'server', name='ut_2')
    )
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('type', sa.Enum('system_cpu_percent', 'user_cpu_percent', 'vsize', name='metrictypes'), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('services_group_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches_story.id'], name='batch_story_fk'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='projects_fk'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='service_fk'),
    sa.ForeignKeyConstraint(['services_group_id'], ['services_groups.id'], name='services_groups_fk'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='teams_fk'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'type', 'service_id', 'services_group_id', name='ut_1')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics')
    op.drop_table('services')
    op.drop_table('services_groups')
    op.drop_table('teams')
    op.drop_table('projects')
    op.drop_table('batches_story')
    # ### end Alembic commands ###
