"""taskflag_table

Revision ID: fb6ca70ec66a
Revises: 34015815507b
Create Date: 2018-07-16 18:11:30.605445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6ca70ec66a'
down_revision = '34015815507b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('services_title_key', 'services', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('services_title_key', 'services', ['title'])
    op.drop_table('task_flags')
    # ### end Alembic commands ###
