export const SET_TIME_FROM_OPTION = "SET_TIME_FROM_OPTION";
export const SET_TIME_UNTIL_OPTION = "SET_TIME_UNTIL_OPTION";
export const SET_TIME_STEP_OPTION = "SET_TIME_STEP_OPTION";

export const SELECT_PEAKS_TARGET = "SELECT_PEAKS_TARGET";
